BEGIN ;
    DROP TABLE enum_master cascade;
    drop table refresh_tokens cascade;
    drop table employee_profiles cascade;
    drop table users cascade;
    drop table cadre_posts cascade;
    drop table cadres cascade;
    drop table posts cascade;
    drop table departments cascade;
    drop table castes cascade;
    drop table genders cascade;
    drop table role_permissions cascade;
    drop table permissions cascade;
    drop table roles cascade;
    drop table zp cascade;
    drop table districts cascade;
COMMIT;